language: python
sudo: required
services:
  - docker
env:
  matrix:
  - PYTHON_VERSION=2 TENSORFLOW_VERSION=1.5
  - PYTHON_VERSION=3 TENSORFLOW_VERSION=1.5
  - PYTHON_VERSION=2 TENSORFLOW_VERSION=1.12
  - PYTHON_VERSION=3 TENSORFLOW_VERSION=1.12
cache:
  directories:
  - /home/travis/.tfsnippet
  - /home/travis/.keras
before_install:
  - docker pull haowenxu/travis-tensorflow-docker:py${PYTHON_VERSION}tf${TENSORFLOW_VERSION}
script:
  - bash scripts/travis-run-tests.sh
